@echo off
echo Installing pandas...
py -m pip install pandas
echo Installing regex...
py -m pip install regex
echo Installing smtplib...
py -m pip install secure-smtplib
echo Installing tqdm...
py -m pip install tqdm
echo Installing requests...
py -m pip install requests
echo Installing BeautifulSoup4...
py -m pip install beautifulsoup4
echo Installing selenium...
py -m pip install selenium

echo Dependencies installed!
pause