@echo off
echo Installing pandas...
py -m pip install pandas
echo Installing regex...
py -m pip install regex
echo Installing localcred...
py -m pip install localcred
echo Installing smtplib...
py -m pip install secure-smtplib
echo Installing tqdm...
py -m pip install tqdm
echo Installing requests...
py -m pip install requests
echo Installing BeautifulSoup4...
py -m pip install beautifulsoup4
echo Installing selenium...
py -m pip install selenium
echo Installing df_to_email...
py -m pip install df_to_email
echo Dependencies installed successfully!
pause